### ISSUE TITLE
安装了你这个之后tableViewcell的删除按钮点不动

### ISSUE THREAD

**Issue by cwxatlm** [kingsic/SGExtensions#3]
你的分类写的有问题,建议你检查一下

我找了一天才找到是你这个库导致我tableViewCell的删除按钮点不动

**Comment by J0nphy** [comment]
我也找了一天才发现这个swizzling的方法有毒：
- (void)SG_sendAction:(SEL)action to:(id)target forEvent:(UIEvent *)event {
    self.SG_eventTimeInterval = self.SG_eventTimeInterval == 0 ? SGEventDefaultTimeInterval : self.SG_eventTimeInterval;
    if (self.isIgnoreEvent){
//        return;
    } else if (self.SG_eventTimeInterval >= 0) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(self.SG_eventTimeInterval * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [self setIsIgnoreEvent:NO];
        });
    }
    self.isIgnoreEvent = YES;
    [self SG_sendAction:action to:target forEvent:event];
}

点删除会调用两次，所以第二次就return掉了，导致commitEditingStyle的方法没触发， @cwxatlm 你试下把return注释掉，就可以了。
